name: CI

on:
  push:
    branches-ignore:
      - main
  pull_request:

jobs:
  ci:
    uses: RawZ06-Studio/.github/.github/workflows/node-ci.yml@main
    secrets: inherit
  
  sonar:
    needs: release
    uses: RawZ06-Studio/.github/.github/workflows/node-ci-sonar.yml@main
    with:
      node_version: '24'
    secrets: inherit