name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: RawZ06-Studio/.github/.github/workflows/node-ci-release.yml@main
    permissions:
      contents: write
    with:
      publishable: false       # application, pas de publish npm
    secrets:
      NEXUS_LOGIN: ${{ secrets.NEXUS_LOGIN }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
  
  sonar:
    needs: release
    uses: RawZ06-Studio/.github/.github/workflows/node-ci-sonar.yml@main
    with:
      node_version: '24'
    secrets:
      NEXUS_LOGIN: ${{ secrets.NEXUS_LOGIN }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  docker:
    needs: release
    uses: RawZ06-Studio/.github/.github/workflows/docker-build-push.yml@main
    with:
      image_name: plandorandomsettingsapi
      dokploy_app_id: Mq6t5feuFE3EwBeeeVbs0
    secrets:
      NEXUS_LOGIN: ${{ secrets.NEXUS_LOGIN }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      DOKPLOY_TOKEN: ${{ secrets.DOKPLOY_TOKEN }}